shared:
  output_path: output/policy_model/150M_nitrogen_future
  n_seq_timesteps: 200
  frame_height: 192
  frame_width: 192
  action_mapping_type: "gamepad"
  gamepad_action_mapping:
    max_buttons: 6
    n_stick_bins: 3
    n_trigger_bins: 17
    stick_deadzone: 0.15
  text_tokenizer_config:
    text_tokenizer_name: "gemma"
    text_embedding_shape: [1, 768]
    text_annotation_model_version: ["gemini-2.5-flash", "gemini-2.5-flash-thinking-0905"]
  tokenizer:
    type: "conv"
    conv_tokenizer_config:
      num_tokens: 1

inference:
  mouse_sampling_approach: "truncated_normal"

policy_model:
  n_transformer_layers: 10
  n_q_head: 16
  n_kv_head: 16
  n_thinking_tokens: 1
  transformer_dim: &transformer_dim 1024
  mask_block_size: 128
  attention_history_len: [200, 200, 200, 200, 200, 200, 200, 200, 200, 200]
  n_kv_sink_tokens: 0
  model_type: "dense"
  action_decoder:
    embed_dim: *transformer_dim

stage3_finetune:
  optim:
    learning_rate: 0.0001
    weight_decay: 0.0001
    beta_1: 0.9
    beta_2: 0.999

  future_vision_target_mode: "future"
  # 推理时不需要实际加载 state_target_tokenizer，但需要设置为非 null
  # 以便 inference.py 正确识别此 checkpoint 为 Stage3FutureVisionLightning 类型
  state_target_tokenizer:
    type: "conv"
    conv_tokenizer_config:
      num_tokens: 1

  validation_step_interval: 20000
  n_validation_steps: &n_validation_steps 200
  save_every_n_steps: 10000
  n_training_steps: 500000
  accumulate_grad_batches: 1

  training_dataset:
    batch_size: &stage3_batch_size 2
    local_prefix: "dataset_nitrogen_toy"
    warn_on_starvation: false
    always_labelled: true
    rand_augmentation:
      fraction_augmented: 1.0
      augmentations:
        - spatial_transform
        - color
        - planckian
        - iso_noise
        - translation
        - random_blur
        - sharpness
    n_preprocess_threads_per_gpu: 1
    preprocessed_chunks_queue_size_per_gpu: 16
    shuffle_buffer_size_per_gpu: 200
    dataset_worker_num_workers_per_gpu: 1
    dataset_worker_prefetch_factor: 2
    shuffled_chunks_queue_size_per_gpu: 2

  validation_datasets:
    - batch_size: *stage3_batch_size
      local_prefix: "dataset_nitrogen_toy"
      validation_name: "overall"
      n_preprocess_threads_per_gpu: &validation_stage3_n_preprocess_threads_per_gpu 8
      preprocessed_chunks_queue_size_per_gpu: &validation_stage3_preprocessed_chunks_queue_size_per_gpu 1
      shuffled_chunks_queue_size_per_gpu: &validation_stage3_shuffled_chunks_queue_size 1
      dataset_worker_prefetch_factor: &validation_stage3_dataset_worker_prefetch_factor 8
      warn_on_starvation: false
      always_labelled: true

wandb:
  enabled: True
  entity: "zjut-cv"
  project: "policy_model"
  exp_name: "150M-local-nitrogen-dataset-future"
