shared:
  output_path: output/policy_model/150M_nitrogen_cuphead_future_action_direct_F18_2head
  n_seq_timesteps: 200
  frame_height: 192
  frame_width: 192
  action_mapping_type: "gamepad_direct"
  gamepad_direct_action_mapping:
    n_stick_bins: 3
    stick_deadzone: 0.15
  tokenizer:
    type: "conv"
    conv_tokenizer_config:
      num_tokens: 1

inference:
  mouse_sampling_approach: "truncated_normal"

policy_model:
  n_transformer_layers: 10
  n_q_head: 16
  n_kv_head: 16
  n_thinking_tokens: 1
  transformer_dim: &transformer_dim 1024
  mask_block_size: 128
  attention_history_len: [200, 200, 200, 200, 200, 200, 200, 200, 200, 200]
  n_kv_sink_tokens: 0
  model_type: "dense"
  n_future_action_tokens: 18
  zero_action_input: true
  action_decoder:
    embed_dim: *transformer_dim

stage3_finetune:
  optim:
    learning_rate: 0.0001
    weight_decay: 0.0001
    beta_1: 0.9
    beta_2: 0.999

  future_vision_target_mode: "future"
  # 推理时不需要实际加载 state_target_tokenizer，但需要设置为非 null
  # 以便 inference.py 正确识别此 checkpoint 为 Stage3FutureVisionLightning 类型
  state_target_tokenizer:
    type: "conv"
    conv_tokenizer_config:
      num_tokens: 1

  validation_step_interval: 999999
  n_validation_steps: 0
  save_every_n_steps: 10000
  n_training_steps: 500000
  accumulate_grad_batches: 1

  training_dataset:
    batch_size: 2
    local_prefix: "cuphead_dataset_converted"
    load_video_name: "192x192.mp4"
    warn_on_starvation: false
    always_labelled: true

wandb:
  enabled: False
  entity: "zjut-cv"
  project: "policy_model"
  exp_name: "150M-nitrogen-cuphead-future-action-direct-F18-2head"
